version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=pbst
      - DB_USER=root
      - DB_PASS=password

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pbst
    volumes:
      - db_data:/var/lib/mysql
      - ./pbst.sql:/docker-entrypoint-initdb.d/pbst.sql

volumes:
  db_data:
